services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    env_file: ./gateway/.env
    depends_on:
      - userServices
      - inventoryServices
      - mailServices
      - paymentServices
      - promotionServices

  userServices:
    build: ./services/userServices
    ports:
      - "3001:3001"
    env_file: ./services/userServices/.env

  mailServices:
    build: ./services/mailServices
    ports:
      - "3002:3002"
    env_file: ./services/mailServices/.env

  inventoryServices:
    build: ./services/inventoryServices
    ports:
      - "3003:3003"
    env_file: ./services/inventoryServices/.env

  paymentServices:
    build: ./services/paymentServices
    ports:
      - "3005:3005"
    env_file: ./services/paymentServices/.env

  promotionServices:
    build: ./services/promotionServices
    ports:
      - "3006:3006"
    env_file: ./services/promotionServices/.env
