services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    env_file: ./gateway/.env
    depends_on:
      - userServices
      - inventoryServices
      - mailServices

  userServices:
    build: ./services/userServices
    ports:
      - "3001:3001"
    env_file: ./services/userServices/.env

  mailServices:
    build: ./services/mailServices
    ports:
      - "3003:3002"
    env_file: ./services/mailServices/.env
